# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.8.0
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: eflow_stage

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Set up DB
          command: npm run stage:prepare
        # environment:
        #   DATABASE_URL: 'postgres://ubuntu@localhost:5432/eflow_staging'
      # - run: yarn test

  deploy-staging:
    docker:
      - image: circleci/node:10.8.0-browsers
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - add_ssh_keys:
          fingerprints:
            - '4d:b5:eb:aa:7e:e6:76:45:56:05:49:34:d6:7f:d6:7c'

      - run:
          name: Rebuild and Start
          command: |
            ssh -o StrictHostKeyChecking=no leoqiu@142.93.24.126 'mkdir -p test/public'

workflows:
  version: 2
  build_and_deploy_staging:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          # filters:
          #   branches:
          #     only: dev
