version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.8.0
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: eflow_test

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Set up DB
          command: npm run test:prepare

      - run: npm run test

  deploy-staging:
    docker:
      - image: circleci/node:10.8.0-browsers
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - run: sudo apt-get install sshpass

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - add_ssh_keys:
          fingerprints:
            - "4d:b5:eb:aa:7e:e6:76:45:56:05:49:34:d6:7f:d6:7c"

      - run:
          name: Rebuild and Start
          command: |
            # -o for answer the question once logged into server
            # -t to use EOF
            # exit to exit the ssh session
            sshpass -p $LEO_EFLOW_SSH_PASS ssh -tt -o StrictHostKeyChecking=no leoqiu@eflows.ucdavis.edu <<EOF 
              rm -rf test3
              rm -rf test4
              mkdir -p test3/public
              mkdir -p test4/public
              exit
            EOF

workflows:
  version: 2
  build_and_deploy_staging:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          # filters:
          #   branches:
          #     only: dev
